config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth_google' 

  root 'sessions#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"
	post '/signup', to: "users#create"

  # get '/auth/facebook/callback', to: 'sessions#omniauth_facebook' 
  # get '/auth/github/callback', to: 'sessions#omniauth_github'  

  resources :users, only: [:new, :create, :show ] 

  resources :reviews, only: [:index, :show, :new, :create, :delete] 

  resources :games do
    resources :reviews, only: [:index, :new, :create, :show]
  end


  resources :publishers do
    resources :games, only: [:index, :new, :create, :show]
  end  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :games
    accepts_nested_attributes_for :games

    def games_attributes=(games_attributes)
        if !games_attributes["title"].blank? && !games_attributes["genre"].blank? && !games_attributes["esrb_rating"].blank? && !games_attributes["platform"].blank?
            self.games = Game.find_or_create_by(games_attributes)
        end
    end

    # def game_attributes=(game_attributes)
    #     game_attributes.values.each do |game_attribute|
    #       game = Game.find_or_create_by(game_attribute)
    #       self.game << game
    #     end
    # end


    validates :name, :based_in, :awards, presence: true 
    

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_publisher, only: [:show, :edit, :update, :destroy]

    def index 
        @publishers = Publisher.all
    end

    def show
    end


    def new
        @publisher = Publisher.new
    end

    def create
    
        @publisher = Publisher.new(publisher_params)
       
        if @publisher.save
            redirect_to publishers_path
        else
            render :new
        end
    end

    def edit
       
    end

    def update
        if @publisher.valid?
            @publisher.update(publisher_params)
            redirect_to publisher_path(@publisher)
        else
            render :edit
        end
    end

    def destroy
        @publisher.destroy
        redirect_to publishers_path
    end
    

    private

    def publisher_params
        params.require(:publisher).permit(:name, :founded, :based_in, :awards, game_attributes: [:title, :genre, :esrb_rating, :platform])
    end

    def find_publisher
        @publisher = Publisher.find(params[:id])
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<%= render partial: "layouts/error", locals: {object: @publisher} %>

<%= form_for @publisher do |p| %>
    
    <%= p.label "name" %><br>
    <%= p.text_field :name %><br>

    <%= p.label "based_in" %><br>
    <%= p.text_field :based_in %><br>

    <%= p.label "awards" %><br>
    <%= p.text_field :awards %><br>
    
    <h4> Games being created by the publisher:</h4>
    <%= p.fields_for :game do |f| %>
       <%= render partial: "games/game_field", locals: {g: f} %>
   <% end %><br>
 
   <%= p.submit %>
 <% end %>

app/views/publishers/edit.html.erb
<h1>Fill out the field below to edit the publisher details: </h1>
<%= render partial: "layouts/error", locals: {object: @publisher} %>

<%= form_for @publisher do |p| %>
    
    <%= p.label "name" %><br>
    <%= p.text_field :name %><br>

    <%= p.label "based_in" %><br>
    <%= p.text_field :based_in %><br>

    <%= p.label "awards" %><br>
    <%= p.text_field :awards %><br>
    
    <%= p.submit %>
<% end %>

app/views/publishers/index.html.erb
<h1>Here are all the Publisher</h1>
        
<% @publishers.each do |publisher|  %>
    ID: <%= publisher.id %><br>
    Name: <%= link_to publisher.name, publisher_games_path(publisher) %> - Founded: <%= publisher.based_in %><hr> <br>
<% end %>

app/views/publishers/new.html.erb
<h1>Fill out the field below to add a publisher</h1>
<%= render partial: "form"  %>

app/views/publishers/show.html.erb
<h1>You have selected <%= @publisher.name%>, here are all the available information for this publisher </h1>

    Publisher Name: <%= @publisher.name %><br>
    Based in: <%= @publisher.based_in%><br>
    Awards won: <%= @publisher.awards%><br>

    <%= link_to "Edit", edit_publisher_path(@publisher)%>
    <%= link_to "Delete", publisher_path(@publisher), method: 'delete' %><hr><br>
 

 
    <h1>To see a list of games from <%= @publisher.name%></h1>
    <%= link_to "Click Here", publisher_games_path(@publisher)%>