config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth_google' 

  root 'sessions#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"
	post '/signup', to: "users#create"

  # get '/auth/facebook/callback', to: 'sessions#omniauth_facebook' 
  # get '/auth/github/callback', to: 'sessions#omniauth_github'  

  resources :users, only: [:new, :create, :show ] 

  resources :reviews, only: [:index, :show, :new, :create, :delete] 

  resources :games do
    resources :reviews, only: [:index, :new, :create, :show]
  end


  resources :publishers do
    resources :games, only: [:index, :new, :create, :show]
  end  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
    belongs_to :publisher
    
    accepts_nested_attributes_for :publisher
    
    def publisher_attributes=(publisher_attributes)
        if !publisher_attributes["name"].blank? && !publisher_attributes["based_in"].blank? && !publisher_attributes["awards"].blank?
            self.publisher = Publisher.find_or_create_by(publisher_attributes)
        end
    end


    # def publisher_attributes=(publisher_attributes)
    #     publisher_attributes.values.each do |publisher_attribute|
    #       publisher = Publisher.find_or_create_by(publisher_attribute)
    #       self.publishers << publisher
    #     end
    # end

    validates :title, presence: true, uniqueness: {case_sensitive: false}, length: {in: 2..50} 
    validates :genre, :esrb_rating, :platform, presence: true
    validates :esrb_rating, numericality: {greater_than_or_equal_to: 0, less_than: 19}


    scope :order_by_esrb_rating, -> {order(esrb_rating: :desc)}
    scope :order_by_publisher, -> {order(:publisher)}


    # def self.order_by_esrb_rating
    #     self.order(esrb_rating: :asc)
    # end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_game, only: [:show, :update, :edit, :destroy]
    layout "game"
    
    def index 

        if params[:publisher_id] && @publisher = Publisher.find(params[:publisher_id])
            @games = @publisher.games
        else
            @games = Game.order_by_esrb_rating
        end

    end

    def show
    end

    def new
        if params[:publisher_id] && @publisher = Publisher.find_by_id(params[:publisher_id])
            @game = Game.new(publisher_id: params[:publisher_id])
            @game = @publisher.games.build
        else
            @game = Game.new
            @game.build_publisher
        end
    end

    def create
        @game = Game.new(game_params)
        if params[:publisher_id] 
            @publisher = Publisher.find_by_id(params[:publisher_id])
        end


        if @game.save
            redirect_to games_path
        else
              @game.build_publisher
            render :new
        end
    end

    def edit

    end

    def update
        if @game.valid?
            @game.update(game_params)
            redirect_to game_path(@game)
        else
            render :edit
        end
    end

    def destroy
        @game.destroy
        redirect_to games_path
    end



    private
    
    def game_params
        params.require(:game).permit(:title, :genre, :esrb_rating, :platform, :publisher_id, publisher_attributes: [:name, :based_in, :awards])
    end

    def find_game
        @game = Game.find(params[:id])
    end
end

app/helpers/games_helper.rb
module GamesHelper
    def fields_for_publisher(g)
        if @publisher
            g.hidden_field :publisher_id, value: @publisher.id
        else
            render partial: "publisher_field", locals: {g: g}    
        end
    end

    def game_index_divergence
        # byebug
        if @publisher 
            render partial: "nested_games"
        else 
            render partial: "all_games" 
         end 
    end

     

end

app/views/games/_all_games.html.erb
<h1>See below for all the games</h1>

<% @games.each do |game|%>  
    Game Id: <%= game.id%><br>
    Name: <%= link_to game.title, game_path(game) %><br>
    Genre: <%= game.genre %><br>
    Rating: <%= game.esrb_rating %><br><br>
    
<% end %>

app/views/games/_all_games_display.html.erb
<% @games.each do |game|%>  
    Name: <%= link_to game.title, game_path(game) %><br>
    Genre: <%= game.genre %><br>
    Rating: <%= game.esrb_rating %><br>
    publisher: <%= game.publisher.name %><hr><br>
<% end %>

app/views/games/_form.html.erb
<%= form_for([@publisher, @game]) do |g| %>
    <%= render partial: "game_field", locals: {g: g} %>
    <%= fields_for_publisher(g)%>
    <br>
    <%= g.submit %>
<% end %>

app/views/games/_game_display.html.erb
<% @publisher.games.each do |game|  %>
    Name: <%= link_to game.title, game_path(game) %><br>
    Genre: <%= game.genre %> <br>
    Rating: <%= game.esrb_rating %><hr><br> 
<% end %>

app/views/games/_game_field.html.erb
<%= g.label "Please enter the game title:", required: true %><br>
<%= g.text_field :title%> <br><br>

<%= g.label "Please enter the game genre:" %><br>
<%= g.text_field :genre %><br><br>

<%= g.label "Please enter the game's ESRB Rating:" %><br>
<%= g.text_field :esrb_rating %><br><br>

<%= g.label "Please enter the game's platform:" %><br>
<%= g.text_field :platform %><br><br>

app/views/games/_nest_free_games.html.erb
<h1>Here are all the games</h1>

<% @games.each do |game|%>  
    Game Id: <%= game.id%><br>
    Name: <%= link_to game.title, game_path(game) %><br>
    Genre: <%= game.genre %><br>
    Rating: <%= game.esrb_rating %><br><br>
    
<% end %>

app/views/games/_nested_games.html.erb
<h1>Here are all the games from <%= @publisher.name%> </h1>
 



<% @publisher.games.each do |g|%>
    <ul>
        <li><%= link_to g.title, publisher_game_path(@publisher, g)%> - <%= g.id%></li>
    </ul>     
<%end%> 


<h3>Want to add another game from <%= @publisher.name %>?</h3>
<%= link_to "Click Here", new_publisher_game_path(@publisher) %>

app/views/games/_publisher_field.html.erb
<h5>Please select a given publisher</h5>

<%= g.collection_select :publisher_id, Publisher.all, :id, :name,{:prompt => "Select Publisher"} %><br>

<p>Dont see the publisher for the game? Add it below:</p><br>

<%= g.fields_for :publisher do |p| %>
    <%= p.label "name" %><br>
    <%= p.text_field :name %><br>

    <%= p.label "based_in" %><br>
    <%= p.text_field :based_in %><br>

    <%= p.label "awards" %><br>
    <%= p.text_field :awards %><br>

<% end %>

app/views/games/_publisher_fields.html.erb
<h5>Please select a publisher</h5>
<%= g.collection_select :publisher_id, Publisher.all, :id, :name%><br>

<p>Dont see the publisher for the game?<br>
Add it below:</p>

<%= g.fields_for :publisher do |p| %>
    <%= p.label "name" %><br>
    <%= p.text_field :name %><br>

    <%= p.label "formation" %><br>
    <%= p.text_field :founded %><br>

    <%= p.label "based_in" %><br>
    <%= p.text_field :based_in %><br>

    <%= p.label "awards" %><br>
    <%= p.text_field :awards %><br>

<% end %>

app/views/games/edit.html.erb
<h1>Please fill out the field below to edit the game details: </h1>
<%= render partial: "layouts/error", locals: {object: @game} %>

<%= render partial: "form" %>

app/views/games/index.html.erb
<%= game_index_divergence %> 

app/views/games/new.html.erb
<h1>Please complete the fields below to Add a New Game</h1>
<%= render partial: "layouts/error", locals: {object: @game} %>

<%= render partial: "form" %>

app/views/games/show.html.erb
<h1>You have selected <%= @game.title%></h1>

<div class="frame">

 <div class="segment">
   <h2>Title: <%= @game.title %></h2>
   <h5>Game Id: <%= @game.id %> </h5>

   <h5>Game Genre: <%= @game.genre %><br></h5>
   <h5>Game ESRB Rating: <%= @game.esrb_rating %><br></h5>
   <h5> Game Platform: <%= @game.platform %><br></h5>
   <h5>Game Publisher: <%= @game.publisher.name%><br><hr></h5>

   <%= link_to "Edit", edit_game_path(@game)%>
   <%= link_to "Write a review", new_game_review_path(@game)%>
   <%= link_to "Delete", game_path(@game), method: 'delete' %>
 </div>

 <div class="segment">
   <h2>Reviews for the game</h2>
   <p>
        <% @game.reviews.each do |review| %>
            From: <%= link_to review.user.username, game_review_path(@game, review) %><br>
            Review Id: <%= review.id %><br>
            Postive aspect rating: <%= review.props %><br>
            Comment postive aspect: <%= review.pro_comment %> <br>
            Negative aspect rating: <%= review.boos %> <br>
            Comment on negative aspect: <%= review.con_comment%> <hr><br>
        <% end %>
   </p>
 </div>
 
</div>



 
   