config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth_google' 

  root 'sessions#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"
	post '/signup', to: "users#create"

  # get '/auth/facebook/callback', to: 'sessions#omniauth_facebook' 
  # get '/auth/github/callback', to: 'sessions#omniauth_github'  

  resources :users, only: [:new, :create, :show ] 

  resources :reviews, only: [:index, :show, :new, :create, :delete] 

  resources :games do
    resources :reviews, only: [:index, :new, :create, :show]
  end


  resources :publishers do
    resources :games, only: [:index, :new, :create, :show]
  end  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :find_review, only: [:show, :destroy]

    def index
        if params[:game_id] && @game = Game.find(params[:game_id])
            @reviews = @game.reviews
        else
            @reviews = Review.order_by_props
        end
    end


    def show
        
    end

    def new
        @game = Game.find_by_id(params[:game_id])
        #   byebug
        @review = @game.reviews.build

    end

    def create
      
    @game = Game.find_by_id(params[:game_id])
       @review = Review.new(review_params)
       @review.user = current_user

        #  byebug
       if @review.save
            redirect_to game_reviews_path(@game, @review)
            #redirect_to game_path(@game)
       else
            render :new
       end
    end


    def destroy
        @review.destroy
        redirect_to reviews_path
    end


    private
    
    def review_params
        params.require(:review).permit(:props, :pro_comment, :boos, :con_comment, :game_id )
    end

    def find_review
        @review = Review.find(params[:id])                

    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def review_index_divergence
        # byebug
        if @game 
            
            render partial: "nested_reviews"
        else 
            
            render partial: "all_reviews" 
         end 
      
    end
end

app/views/reviews/_all_reviews.html.erb
<h1>Here are all the reviews for all of the games </h1>


<% @reviews.each do |review| %>
    Game Id: <%= review.game_id %> <br>
    Review Id: <%= review.id %><br>
    postive rating: <%=  review.props %><br>
    postive comment: <%=  review.pro_comment %><br>
    negative rating: <%=  review.boos %><br>
    postive comment: <%=  review.con_comment %><br>
    by <%= link_to review.user.username, review_path(review) %><hr>
<% end %>

app/views/reviews/_nested_reviews.html.erb
<h1>Here are all the reviews for the game <%= @game.title%> </h1>


<% @reviews.each do |r| %>
    Game Id: <%= r.game_id %> <br>
    Review Id: <%= r.id %><br>
    postive rating: <%=  r.props %><br>
    postive comment: <%=  r.pro_comment %><br>
    negative rating: <%=  r.boos %><br>
    postive comment: <%=  r.con_comment %><br>
    From User: <%= link_to r.user.username, game_review_path(@game,r) %><hr>
<% end %>

app/views/reviews/index.html.erb
<%= review_index_divergence%>

app/views/reviews/new.html.erb
<%= render partial: "layouts/error", locals: {object: @review} %>


<%= form_for([@game, @review]) do |f|  %>
    
    <%= f.label "Please rate the outstanding aspect of the game (1-5)" %><br>
    <%= f.select :props, options_for_select(1..5) %><br>
   
    <%= f.label "Comment on Postive aspect of the game" %><br>
    <%= f.text_area :pro_comment%><br>

    <%= f.label "Please rate the negative aspect of the game (1-5)" %><br>
    <%= f.select :boos, options_for_select(1..5) %><br>

    <%= f.label "Comment on negative aspect of the game" %><br>
    <%= f.text_area :con_comment%><br>

    <%= f.hidden_field :game_id, value: @game.id%>
    <%= f.submit %>
<%end %>

app/views/reviews/show.html.erb
postive rating: <%= @review.props %><br>
comment on positive game aspect:<%= @review.pro_comment %><br>

deficiency rating: <%= @review.boos %><br>
Comment for negative game aspect: <%= @review.con_comment %><br>

<%= link_to "Delete Review", review_path(@review), method: 'delete' %>