config/routes.rb
Rails.application.routes.draw do
  
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth_google' 

  root 'sessions#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  get '/signup', to: "users#new"
	post '/signup', to: "users#create"

  # get '/auth/facebook/callback', to: 'sessions#omniauth_facebook' 
  # get '/auth/github/callback', to: 'sessions#omniauth_github'  

  resources :users, only: [:new, :create, :show ] 

  resources :reviews, only: [:index, :show, :new, :create, :delete] 

  resources :games do
    resources :reviews, only: [:index, :new, :create, :show]
  end


  resources :publishers do
    resources :games, only: [:index, :new, :create, :show]
  end  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited from being saved:</h2>

  <ul>
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class = "topnav">
      <% if logged_in?  %>
        <%= link_to "All Games", games_path %>
        <%= link_to "All publisher", publishers_path%>
        <%= link_to "All reviews", reviews_path %>
        <%= link_to "Add Game", new_game_path %>
        <%= link_to "Add Publisher", new_publisher_path%>
        <%= link_to "Log Out", logout_path, method: 'delete' %>
      <% else %>
        <%= link_to "Sign up", signup_path %> 
        <%= link_to "Log In", login_path %> 
      <% end %>
    </div>
  
    <div >
      <% flash.each do |type, msg|%>
        <div class="error_hint">
          <%= msg%>
        </div>
      <%end%>

      <%= yield %>  
    </div>
    
  </body>

</html>

app/views/layouts/error_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'errors', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 
  <div>
    <%= yield %>  
  </div>
  
  </body>
</html>


<h1>UH OH, you encountered an error!!!</h1>
<h3>See below for hints to your error:</h3>
<%= @error_hint%><br><br>
<%= link_to "Clicke Here", publishers_path %> to return to the Publisher's index <br>
<%= link_to "Clicke Here", games_path %> to return to the Game's index <br>
<%= link_to "Clicke Here", reviews_path %> to return to the Review's index

app/views/layouts/game.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Rails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="header">
    <h1>Welcome to the Game page</h1>
    <p>See below for all the available information:</p>
  </div>

  <div class = "topnav">
    <% if logged_in?  %>
      <%= link_to "All Games", games_path %>
      <%= link_to "All publisher", publishers_path%>
      <%= link_to "All reviews", reviews_path %>
      <%= link_to "Add Game", new_game_path %>
      <%= link_to "Add Publisher", new_publisher_path%>
      <%= link_to "Log Out", logout_path, method: 'delete' %>
    <% else %>
      <%= link_to "Sign up", signup_path %> 
      <%= link_to "Log In", login_path %> 
    <% end %>
  </div>  

 
  <div>
    <%= yield %>  
  </div>
  
  </body>
</html>